# This workflow will build and test a Java project with Maven

name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Build and run Tests
        run: mvn clean verify
      - name: Verify Integration Test Support was not changed
        run: ./solace-integration-test-support/scripts/validate_submodule_not_changed.sh
